version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.28
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_NAME
    ports:
      - $MYSQL_EXTERNAL_PORT:$MYSQL_INTERNAL_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  eureka:
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/eureka
    env_file: ./.env
    ports:
      - $EUREKA_EXTERNAL_PORT:$EUREKA_INTERNAL_PORT
    volumes:
      - eureka:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  usercrud:
    depends_on:
      - mysqldb
      - eureka
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/user-crud
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $USERCRUD_EXTERNAL_PORT:$USERCRUD_INTERNAL_PORT
    volumes:
      - usercrud:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  buyingmarket:
    depends_on:
      - mysqldb
      - eureka
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/buying-market
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      API_USERCRUD: http://usercrud:$USERCRUD_INTERNAL_PORT
      API_SECURITIES: http://securities:$SECURITIES_INTERNAL_PORT
    ports:
      - $MARKET_EXTERNAL_PORT:$MARKET_INTERNAL_PORT
    volumes:
      - buyingmarket:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  gateway:
    depends_on:
      - usercrud
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/gateway
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      ZUUL_ROUTES_USER_URL: http://usercrud:$USERCRUD_INTERNAL_PORT/api/users
      ZUUL_ROUTES_SECURITIES_URL: http://securities:$SECURITIES_INTERNAL_PORT/api
      ZUUL_ROUTES_BUYINGMARKET_URL: http://buyingmarket:$MARKET_INTERNAL_PORT/api
      ZUUL_ROUTES_STOCKINFO_URL: http://pythonflask:$PYTHONFLASK_INTERNAL_PORT
    ports:
      - $GATEWAY_EXTERNAL_PORT:$GATEWAY_INTERNAL_PORT
    networks:
      - nginx
      - backend
    volumes:
      - gateway:/root/.m2
    stdin_open: true
    tty: true


  securities:
    depends_on:
      - mysqldb
      - eureka
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/securities
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $SECURITIES_EXTERNAL_PORT:$SECURITIES_INTERNAL_PORT
    volumes:
      - securities:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  accounttransaction:
    depends_on:
      - mysqldb
      - securities
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/accounttransaction
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      API_USERCRUD: http://usercrud:$USERCRUD_INTERNAL_PORT
      API_SECURITIES: http://securities:$SECURITIES_INTERNAL_PORT
    ports:
      - $TRANSACTION_EXTERNAL_PORT:$TRANSACTION_INTERNAL_PORT
    volumes:
      - accounttransaction:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  frontend:
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/frontend
    ports:
      - $FRONTEND_EXTERNAL_PORT:$FRONTEND_INTERNAL_PORT
    networks:
      - nginx

  pythonflask:
    image: ghcr.io/raf-si-2021/osiguranjeraf2022/python-flask
    env_file: ./.env
    ports:
      - $PYTHONFLASK_EXTERNAL_PORT:$PYTHONFLASK_INTERNAL_PORT
    volumes:
      - pythonflask:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  redis_db:
    image: redis:3.2.8
    env_file: ./.env
    environment:
      REDIS_HOSTNAME=redis_db
      REDIS_PORT=$REDIS_INTERNAL_PORT
      CACHEEXPIRYTIME=60
    ports:
      - $REDIS_EXTERNAL_PORT:$REDIS_INTERNAL_PORT
    tty: true
    networks:
      - backend

volumes:
  db:
  eureka:
  gateway:
  usercrud:
  securities:
  buyingmarket:
  pythonflask:
  accounttransaction:

networks:
  nginx:
    driver: bridge
  backend:
    driver: bridge