name: Build docker images and push

on:
  push:
    branches:
      - 'master'

concurrency: ci-${{ github.ref }}

jobs:
  docker-build-and-push:
    name: Build and push the images from the Osiguranje-Back repository
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      # Builds multi arch images :)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Set up secrets on the repository
          password: ${{ secrets.GITHUB_TOKEN }} # Get this on Docker Hub

      - name: Build and push gateway-app
        uses: docker/build-push-action@v2
        with:
          context: ./gateway-app
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/gateway

      - name: Build and push eureka
        uses: docker/build-push-action@v2
        with:
          context: ./eureka
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/eureka

      - name: Build and push user-crud
        uses: docker/build-push-action@v2
        with:
          context: ./user-crud
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/user-crud

      - name: Build and push securities
        uses: docker/build-push-action@v2
        with:
          context: ./securities
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/securities

      - name: Build and push python-service
        uses: docker/build-push-action@v2
        with:
          context: ./python-service
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/python-flask

      - name: Build and push buying-market
        uses: docker/build-push-action@v2
        with:
          context: ./buying-market
          push: true
          tags: ghcr.io/raf-si-2021/osiguranjeraf2022/buying-market


